
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GABS
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtpetugas = new javax.swing.JTextField();
        txtresi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkeluar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        rdMotor = new javax.swing.JRadioButton();
        rdMobil = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JButton();
        txtmasuk = new javax.swing.JTextField();
        txtpol = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 7));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENITIPAN KENDARAAN TELKOM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 20, 470, 28);

        tgl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tgl);
        tgl.setBounds(680, 30, 140, 30);

        waktu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(waktu);
        waktu.setBounds(690, 70, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1030, 120);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ISIAN DATA PENITIPAN KENDARAAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(null);
        jPanel1.add(txtpetugas);
        txtpetugas.setBounds(10, 50, 290, 30);
        jPanel1.add(txtresi);
        txtresi.setBounds(10, 110, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama Petugas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 30, 140, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("No Resi");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 90, 60, 14);
        jPanel1.add(txtkeluar);
        txtkeluar.setBounds(10, 350, 290, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("No Pol");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 150, 60, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Jenis Kendaraan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 210, 140, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tanggal Masuk");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 270, 140, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tanggal Keluar");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 330, 140, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Hari Penitipan");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 390, 120, 14);
        jPanel1.add(txtHari);
        txtHari.setBounds(10, 410, 70, 30);

        jLabel3.setText("Hari");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 414, 30, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total Harga");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 450, 120, 14);

        txtHarga.setEditable(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga);
        txtHarga.setBounds(10, 470, 290, 30);

        buttonGroup1.add(rdMotor);
        rdMotor.setText("Sepeda Motor");
        jPanel1.add(rdMotor);
        rdMotor.setBounds(10, 230, 100, 30);

        buttonGroup1.add(rdMobil);
        rdMobil.setText("Mobil");
        jPanel1.add(rdMobil);
        rdMobil.setBounds(190, 230, 110, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(120, 413, 80, 30);
        jPanel1.add(txtmasuk);
        txtmasuk.setBounds(10, 290, 290, 30);
        jPanel1.add(txtpol);
        txtpol.setBounds(10, 170, 290, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 130, 360, 530);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        btnEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit);
        btnEdit.setBounds(450, 10, 80, 30);

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd);
        btnAdd.setBounds(10, 10, 80, 30);

        Reset.setBackground(new java.awt.Color(102, 102, 102));
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Clear");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset);
        Reset.setBounds(220, 10, 80, 30);

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(110, 10, 80, 30);

        btnRefresh.setBackground(new java.awt.Color(102, 102, 102));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh);
        btnRefresh.setBounds(330, 10, 90, 30);

        print.setBackground(new java.awt.Color(102, 102, 102));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(550, 10, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(390, 130, 640, 50);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Petugas", "no_resi", "No Pol", "Jenis kendaraan", "Tanggal Masuk", "Tanggal keluar", "Total Harga"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 0, 620, 460);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(390, 190, 640, 470);

        setBounds(0, 0, 1047, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        if ("".equals(txtpetugas.getText()) ||"".equals(txtresi.getText()) || "".equals(txtpol.getText()) ||"".equals(txtmasuk.getText())||"".equals(txtkeluar.getText())||"".equals(txtHari.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String JK = "";

            if (rdMotor.isSelected())
            {
                JK = "Sepeda Motor";
            } else{
                JK = "Mobil";
            }

            String SQL = "UPDATE t_titipkendaraan SET"
            + "WHERE petugas='"+txtpetugas.getText()+"',"
            + "WHERE no_resi='"+txtresi.getText()+"',"
            + "WHERE no_pol='"+txtkeluar.getText()+"',"
            + "WHERE jk='"+JK+"',"
            + "WHERE t_masuk='"+txtmasuk.getText()+"'," 
            +"WHERE t_keluar='"+txtkeluar.getText()+"',"
            +"WHERE harga='"+txtHarga.getText()+"'  WHERE no_resi='"+txtresi.getText()+"'";
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    
        if ("".equals(txtpetugas.getText()) || "".equals(txtresi.getText()) ||
            "".equals(txtpol.getText()) || "".equals(txtmasuk.getText()) || "".equals(txtkeluar.getText()) || "".equals(txtHarga.getText())  )
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }

        else
        {
           
          String JK = "";
          if (rdMotor.isSelected())
            {
                JK = "Sepeda Motor";
            }
            else
            {
                JK = "Mobil";
            }
          
            String SQL = "INSERT INTO t_titipkendaraan (petugas,no_resi,no_pol,jk,t_masuk,t_keluar,harga) "
            + "VALUES('"+txtpetugas.getText()+"',"
                    + "'"+txtresi.getText()+"',"
                    + "'"+txtpol.getText()+"',"
                    + "'"+JK+"',"
                    + "'"+txtmasuk.getText()+"',"
                    + "'"+txtkeluar.getText()+"',"
                    + "'"+txtHarga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            
            
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        txtresi.setText("");
        txtpetugas.setText("");
        txtkeluar.setText("");
        buttonGroup1.clearSelection();
        txtmasuk.setText("");
        txtkeluar.setText("");
        txtHarga.setText("");
      
    }//GEN-LAST:event_ResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();

        if (baris != -1)
        {
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_titipkendaraan WHERE no_resi='"+txtresi.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }

        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

        MessageFormat header = new MessageFormat("Data Penitipan Barang Telkom");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}     ");
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);

        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
    
      int baris = tblData.getSelectedRow();
        if (baris != -1) {
            txtpetugas.setText(tblData.getValueAt(baris,0).toString());
            txtresi.setText(tblData.getValueAt(baris,1).toString());
            txtpol.setText(tblData.getValueAt(baris,2).toString());
            if ("Sepeda Motor".equals(tblData.getValueAt(baris,3).toString())) {
                rdMotor.setSelected(true);
            }else{
                rdMobil.setSelected(true);
            }
            txtmasuk.setText(tblData.getValueAt(baris,4).toString());
             txtkeluar.setText(tblData.getValueAt(baris,5).toString());
            txtHarga.setText(tblData.getValueAt(baris,6).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int hrg = Integer.parseInt(txtHari.getText());
        int total = hrg*3000;
        txtHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton print;
    private javax.swing.JRadioButton rdMobil;
    private javax.swing.JRadioButton rdMotor;
    private javax.swing.JTable tblData;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHari;
    private javax.swing.JTextField txtkeluar;
    private javax.swing.JTextField txtmasuk;
    private javax.swing.JTextField txtpetugas;
    private javax.swing.JTextField txtpol;
    private javax.swing.JTextField txtresi;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"petugas","no_resi","no_pol","jk","t_masuk","t_keluar","harga"};
    DefaultTableModel dtm = new DefaultTableModel(null,kolom);
    String SQL = "SELECT * FROM t_titipkendaraan";
    ResultSet rs = KoneksiDB.executeQuery(SQL);
    try {
        while (rs.next()){
        String Petugas = rs.getString(1);
        String Resi = rs.getString(2);
         String Pol = rs.getString(3);
        String JenisKendaraan = "";
            if ("Sepeda Motor".equals(rs.getString(4))) {
                JenisKendaraan = "Sepeda Motor";
            }else{
                JenisKendaraan = "Mobil";
            }
            String masuk = rs.getString(5);
            String keluar = rs.getString(6);
            String harga = rs.getString(7);
            String data[] = {Petugas,Resi,Pol,JenisKendaraan,masuk,keluar,harga};
            dtm.addRow(data);
        }   
    } catch (SQLException ex){
        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
    }
    tblData.setModel(dtm);
    }
    
    
}
